# Gather here most of the useful parameter for a given peer
development: &base
  # Manager settings:
  # the manager who launched the peer,
  # or the manager itself if the current peer is a manager
  communication:
    ip : localhost
    manager_port : 3100
    # Choose a prefered port to spawn peer if not available, find_port will look for others
    default_spawn_port : 10000

  # First peer to spawn
  # A special name is manager to spawn a lightweight server used to launch other peers
  peer:
    # name for the current peer, could be overrride by the ENV['USERNAME'] variable
    username: manager
    protocol: http
    ip: localhost
    ports_used: 3
    # store the port on which the web server listen for requests, you can give a
    # default value to this otherwise find_port will look for available starting
    # from default_spawn_port of the manager
    web_port: 10000
    # default value for the port on which the webdamlog engine listen although it
    # will be defined by find_port
    wdl_engine_port: 20000
    #Which program is loaded by default by the peer.
    program:
      name : prog1.wl
      author : johndoe
      source : app/assets/wlprogram/prog1.wl
      
test:
  communication:
    manager_port : 4100
    default_spawn_port : 30000
  peer:
    username: manager
    protocol : http
    ip : localhost
    ports_used : 5
    root_port : 10000
    wdl_engine_port : 20000
    program:
      name : prog1.wl
      author : johndoe
      source : app/assets/wlprogram/prog1.wl

production:
  <<: *base
