described_rules:
  drule1:
    description: Get all the titles for my pictures
    rule : collection int query1(title*);rule query2@local($title):-pictures@local($title,$_,$_,$_);
    role: query
  drule2:
    description: Get all pictures from all my friends
    rule : collection int query2(title*,contact*,id*,image_url*); rule query2@local($title, $contact, $id, $image_url):- contact@local($contact, $_, $_, $_, $_),pictures@$contact($title, $contact, $id, $image_url);  
    role: query
  drule3:
    description: Get all my pictures with rating higher or equal to 5
    rule : collection int query3(title*,contact*,id*,image_url*); rule query3@local($title,$contact,$id,$image_url):- pictures@local($title,$contact,$id,$image_url),rating@sigmod_peer($id,$rating),rating>=5;
    role: query
  # drule4:
    # description ; Get the ten best rated pictures #Find how to pick limited number of results syntax
    # rule :
  drule5:
    description: Create a friends relations and insert all contacts who commented on one of my pictures. Finally include myself. 
    rule : collection ext persistent friends@local(name*,group*);rule friends@local($name,"commenters"):- pictures@local($_,$_,$id,$_),comments@local($id,$name,$_,$_);
    role: update
  drule6: 
    description: Send to contact all pictures taken last week by our common friends and me at a given location
    rule : rule pictures@"contact"($title, $contact, $id, $image_url):- friends@local("contact",$group),friends@local($peer,$group),pictures@$peer($title,$contact,$id,$image_url),picturelocation@$peer($id,"given location");    
    role: update