contacts:
  contact1:
    name: Emilien
    peerlocation : SIGMOD_peer
    email: Emilien.antoine@inria.fr
    facebook : Emilien Antoine
  contact2:
    name: Julia
    peerlocation : SIGMOD_peer
    email: stoyanovich@drexel.edu
    facebook : stoyanovich@drexel.edu
  contact3:
    name: Gerome
    peerlocation : SIGMOD_peer
    email: miklau@cs.umass.edu
    facebook : Gerome Miklau
  contact4:
    name: Serge
    peerlocation : SIGMOD_peer
    email: serge.abiteboul@inria.fr
    facebook : Serge Abiteboul
pictures:
  picture1:
    title: nemo
    url : http://1.bp.blogspot.com/-Gv648iUY5p0/UD8rqW3deSI/AAAAAAAAACA/MrG4KxFyM5A/s400/Fish.jpeg
  picture2:
    title: wave
    url : http://fc3arch.files.wordpress.com/2011/08/big_wave.jpg
  picture3:
    title: fire
    url : http://4.bp.blogspot.com/-tiN8G5YbB5g/UEj6Cf3HwuI/AAAAAAAAAVY/P8ockeqrJzI/s1600/FireBIG.jpg
  picture4:
    title: mountain
    url : http://limchinwoon.files.wordpress.com/2013/02/mountain_7.jpg    
locations:
  location1:
    title: nemo
    location: Bali, Indonesia
  location2:
    title: wave
    location: Sydney, Australia
  location3:
    title: fire
    location: Somewhere far far away
  location4:
    title: mountain
    location : Alberta, Canada
ratings:
  rating1:
    title:nemo
    rating:3
  rating2:
    title:wave
    rating:5
  rating3:
    title:fire
    rating:4
  rating4:
    title:mountain
    rating:3
